"Resource/LoadingDialog.res"
{
	"LoadingDialog"
	{
		"ControlName"			"Frame"
		"fieldName"				"LoadingDialog"
		"xpos"					"c-240"
		"ypos"					"c150"
		"wide"					"480"
		"tall"					"158"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"settitlebarvisible"	"0"
		"settitlevisible"		"0"
		"paintbackground"		"1"
		"paintbackgroundtype"	"2"
		"paintborder"			"0"
		"bgcolor_override"		"12 14 22 252"
	}
	"Label1"
	{
		"ControlName"			"Label"
		"fieldName"				"Label1"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"480"
		"tall"					"24"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"Connection Failed"
		"textAlignment"			"center"
		"brighttext"			"1"
		"fgcolor_override"		"120 175 255 255"
	}
	"InfoLabel"
	{
		"ControlName"			"Label"
		"fieldName"				"InfoLabel"
		"xpos"					"40"
		"ypos"					"52"
		"wide"					"400"
		"tall"					"44"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				""
		"textAlignment"			"center"
		"wrap"					"1"
		"brighttext"			"1"
		"fgcolor_override"		"235 242 255 255"
	}
	"CopyButton"
	{
		"ControlName"			"Button"
		"fieldName"				"CopyButton"
		"xpos"					"128"
		"ypos"					"108"
		"wide"					"104"
		"tall"					"30"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"Copy"
		"textAlignment"			"center"
		"command"				"Copy"
		"paintbackground"		"1"
		"paintborder"			"0"
		"defaultFgColor_override"	"210 225 248 255"
		"defaultBgColor_override"	"38 44 58 255"
		"armedFgColor_override"		"255 255 255 255"
		"armedBgColor_override"		"54 62 82 255"
		"depressedFgColor_override"	"255 255 255 255"
		"depressedBgColor_override"	"30 36 48 255"
	}
	"CancelButton"
	{
		"ControlName"			"Button"
		"fieldName"				"CancelButton"
		"xpos"					"248"
		"ypos"					"108"
		"wide"					"104"
		"tall"					"30"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"Close"
		"textAlignment"			"center"
		"command"				"Cancel"
		"Default"				"1"
		"paintbackground"		"1"
		"paintborder"			"0"
		"defaultFgColor_override"	"255 255 255 255"
		"defaultBgColor_override"	"35 135 237 220"
		"armedFgColor_override"		"255 255 255 255"
		"armedBgColor_override"		"35 135 237 255"
		"depressedFgColor_override"	"255 255 255 255"
		"depressedBgColor_override"	"24 104 196 255"
	}
	"progress"
	{
		"ControlName"			"ProgressBar"
		"fieldName"				"Progress"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"fgcolor_override"		"0 0 0 0"
		"bgcolor_override"		"0 0 0 0"
	}
	"Progress2"
	{
		"ControlName"			"ProgressBar"
		"fieldName"				"Progress2"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"fgcolor_override"		"0 0 0 0"
		"bgcolor_override"		"0 0 0 0"
	}
	"SecondaryProgressLabel"
	{
		"ControlName"			"Label"
		"fieldName"				"SecondaryProgressLabel"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"labelText"				""
	}
	"TimeRemainingLabel"
	{
		"ControlName"			"Label"
		"fieldName"				"TimeRemainingLabel"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"labelText"				""
	}
	"Divider1"
	{
		"ControlName"			"Divider"
		"fieldName"				"Divider1"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
	}
	"BannerAd"
	{
		"ControlName"			"HTML"
		"fieldName"				"BannerAd"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
	}
}
