"Resource/LoadingDialog.res"
{
	"LoadingDialog"
	{
		"ControlName"			"Frame"
		"fieldName"				"LoadingDialog"
		"xpos"					"r10"
		"ypos"					"b10"
		"wide"					"400"
		"tall"					"65"
		"settitlebarvisible"	"0"
		"enabled"				"1"
		"paintbackground"		"0"
		"paintborder"			"0"
	}
	"InfoLabel"
	{
		"ControlName"			"Label"
		"fieldName"				"InfoLabel"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"labelText"				""
		"defaultFgColor_override"	"0 0 0 0"
	}
	"progress"
	{
		"ControlName"			"ProgressBar"
		"fieldName"				"Progress"
		"xpos"					"10"
		"ypos"					"33"
		"wide"					"310"
		"tall"					"1"
		"paintborder"			"0"
		"fgcolor_override"		"0 0 0 0"
		"bgcolor_override"		"0 0 0 0"
	}
	"CancelButton"
	{
		"ControlName"			"Button"
		"fieldName"				"CancelButton"
		"xpos"					"320"
		"ypos"					"5"
		"wide"					"66"
		"tall"					"22"
		"labelText"				""
		"command"				"Cancel"
		"paintbackground"		"0"
		"paintborder"			"0"
		"defaultFgColor_override"		"0 0 0 0"
		"defaultBgColor_override"		"0 0 0 0"
		"armedFgColor_override"			"0 0 0 0"
		"armedBgColor_override"			"0 0 0 0"
		"depressedFgColor_override"		"0 0 0 0"
		"depressedBgColor_override"		"0 0 0 0"
	}
	"CopyButton"
	{
		"ControlName"			"Button"
		"fieldName"				"CopyButton"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"labelText"				""
		"defaultBgColor_override"	"0 0 0 0"
		"defaultFgColor_override"	"0 0 0 0"
	}
	"Progress2"
	{
		"ControlName"			"ProgressBar"
		"fieldName"				"Progress2"
		"xpos"					"-9999"
		"ypos"					"-9999"
		"wide"					"1"
		"tall"					"1"
		"visible"				"0"
		"fgcolor_override"		"0 0 0 0"
		"bgcolor_override"		"0 0 0 0"
	}
}
